#!/bin/bash
# Generates German pronunciation audio (M4A/AAC) using the macOS `say` command
# with the German voice "Anna". Output goes into ./audio/ next to the markdown.
#
# Re-run any time after adding new entries.

set -e

VOICE="Anna"
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
AUDIO_DIR="$ROOT_DIR/audio"

mkdir -p "$AUDIO_DIR/alphabet" "$AUDIO_DIR/numbers" \
         "$AUDIO_DIR/phrases/welcome" \
         "$AUDIO_DIR/phrases/chapter1" \
         "$AUDIO_DIR/phrases/chapter2"

gen() {
  # gen <output_path> <german_text>
  local out="$1"; shift
  local text="$*"
  if [ ! -f "$out" ]; then
    say -v "$VOICE" -o "$out" --data-format=aac "$text"
    echo "  + $out"
  fi
}

echo "== Alphabet =="
gen "$AUDIO_DIR/alphabet/a.m4a"  "A"
gen "$AUDIO_DIR/alphabet/b.m4a"  "B"
gen "$AUDIO_DIR/alphabet/c.m4a"  "C"
gen "$AUDIO_DIR/alphabet/d.m4a"  "D"
gen "$AUDIO_DIR/alphabet/e.m4a"  "E"
gen "$AUDIO_DIR/alphabet/f.m4a"  "F"
gen "$AUDIO_DIR/alphabet/g.m4a"  "G"
gen "$AUDIO_DIR/alphabet/h.m4a"  "H"
gen "$AUDIO_DIR/alphabet/i.m4a"  "I"
gen "$AUDIO_DIR/alphabet/j.m4a"  "J"
gen "$AUDIO_DIR/alphabet/k.m4a"  "K"
gen "$AUDIO_DIR/alphabet/l.m4a"  "L"
gen "$AUDIO_DIR/alphabet/m.m4a"  "M"
gen "$AUDIO_DIR/alphabet/n.m4a"  "N"
gen "$AUDIO_DIR/alphabet/o.m4a"  "O"
gen "$AUDIO_DIR/alphabet/p.m4a"  "P"
gen "$AUDIO_DIR/alphabet/q.m4a"  "Q"
gen "$AUDIO_DIR/alphabet/r.m4a"  "R"
gen "$AUDIO_DIR/alphabet/s.m4a"  "S"
gen "$AUDIO_DIR/alphabet/t.m4a"  "T"
gen "$AUDIO_DIR/alphabet/u.m4a"  "U"
gen "$AUDIO_DIR/alphabet/v.m4a"  "V"
gen "$AUDIO_DIR/alphabet/w.m4a"  "W"
gen "$AUDIO_DIR/alphabet/x.m4a"  "X"
gen "$AUDIO_DIR/alphabet/y.m4a"  "Y"
gen "$AUDIO_DIR/alphabet/z.m4a"  "Z"
gen "$AUDIO_DIR/alphabet/ae.m4a" "Ä"
gen "$AUDIO_DIR/alphabet/oe.m4a" "Ö"
gen "$AUDIO_DIR/alphabet/ue.m4a" "Ü"
gen "$AUDIO_DIR/alphabet/ss.m4a" "Eszett"
gen "$AUDIO_DIR/alphabet/full.m4a" "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"

echo "== Numbers 0-20 =="
gen "$AUDIO_DIR/numbers/0.m4a"  "null"
gen "$AUDIO_DIR/numbers/1.m4a"  "eins"
gen "$AUDIO_DIR/numbers/2.m4a"  "zwei"
gen "$AUDIO_DIR/numbers/3.m4a"  "drei"
gen "$AUDIO_DIR/numbers/4.m4a"  "vier"
gen "$AUDIO_DIR/numbers/5.m4a"  "fünf"
gen "$AUDIO_DIR/numbers/6.m4a"  "sechs"
gen "$AUDIO_DIR/numbers/7.m4a"  "sieben"
gen "$AUDIO_DIR/numbers/8.m4a"  "acht"
gen "$AUDIO_DIR/numbers/9.m4a"  "neun"
gen "$AUDIO_DIR/numbers/10.m4a" "zehn"
gen "$AUDIO_DIR/numbers/11.m4a" "elf"
gen "$AUDIO_DIR/numbers/12.m4a" "zwölf"
gen "$AUDIO_DIR/numbers/13.m4a" "dreizehn"
gen "$AUDIO_DIR/numbers/14.m4a" "vierzehn"
gen "$AUDIO_DIR/numbers/15.m4a" "fünfzehn"
gen "$AUDIO_DIR/numbers/16.m4a" "sechzehn"
gen "$AUDIO_DIR/numbers/17.m4a" "siebzehn"
gen "$AUDIO_DIR/numbers/18.m4a" "achtzehn"
gen "$AUDIO_DIR/numbers/19.m4a" "neunzehn"

echo "== Tens =="
gen "$AUDIO_DIR/numbers/20.m4a"  "zwanzig"
gen "$AUDIO_DIR/numbers/30.m4a"  "dreißig"
gen "$AUDIO_DIR/numbers/40.m4a"  "vierzig"
gen "$AUDIO_DIR/numbers/50.m4a"  "fünfzig"
gen "$AUDIO_DIR/numbers/60.m4a"  "sechzig"
gen "$AUDIO_DIR/numbers/70.m4a"  "siebzig"
gen "$AUDIO_DIR/numbers/80.m4a"  "achtzig"
gen "$AUDIO_DIR/numbers/90.m4a"  "neunzig"
gen "$AUDIO_DIR/numbers/100.m4a" "einhundert"

echo "== Combo numbers =="
gen "$AUDIO_DIR/numbers/21.m4a"   "einundzwanzig"
gen "$AUDIO_DIR/numbers/22.m4a"   "zweiundzwanzig"
gen "$AUDIO_DIR/numbers/31.m4a"   "einunddreißig"
gen "$AUDIO_DIR/numbers/38.m4a"   "achtunddreißig"
gen "$AUDIO_DIR/numbers/44.m4a"   "vierundvierzig"
gen "$AUDIO_DIR/numbers/67.m4a"   "siebenundsechzig"
gen "$AUDIO_DIR/numbers/83.m4a"   "dreiundachtzig"
gen "$AUDIO_DIR/numbers/99.m4a"   "neunundneunzig"
gen "$AUDIO_DIR/numbers/101.m4a"  "hunderteins"
gen "$AUDIO_DIR/numbers/136.m4a"  "hundertsechsunddreißig"
gen "$AUDIO_DIR/numbers/144.m4a"  "hundertvierundvierzig"
gen "$AUDIO_DIR/numbers/200.m4a"  "zweihundert"
gen "$AUDIO_DIR/numbers/1000.m4a" "tausend"

echo "== Welcome phrases =="
gen "$AUDIO_DIR/phrases/welcome/guten-morgen.m4a"           "Guten Morgen!"
gen "$AUDIO_DIR/phrases/welcome/wie-geht-es-ihnen.m4a"      "Wie geht es Ihnen?"
gen "$AUDIO_DIR/phrases/welcome/danke-gut-und-ihnen.m4a"    "Danke, gut! Und Ihnen?"
gen "$AUDIO_DIR/phrases/welcome/wie-gehts-dir.m4a"          "Hallo! Wie geht's dir?"
gen "$AUDIO_DIR/phrases/welcome/super-danke-und-dir.m4a"    "Super, danke. Und dir?"
gen "$AUDIO_DIR/phrases/welcome/entschuldigung.m4a"         "Entschuldigung?"
gen "$AUDIO_DIR/phrases/welcome/kein-problem.m4a"           "Okay, kein Problem."
gen "$AUDIO_DIR/phrases/welcome/ins-zentrum-bitte.m4a"      "Ins Zentrum, bitte."
gen "$AUDIO_DIR/phrases/welcome/noch-mal.m4a"               "Noch mal!"
gen "$AUDIO_DIR/phrases/welcome/auf-wiedersehen.m4a"        "Auf Wiedersehen!"
gen "$AUDIO_DIR/phrases/welcome/tschuess.m4a"               "Tschüss!"
gen "$AUDIO_DIR/phrases/welcome/machs-gut.m4a"              "Mach's gut!"
gen "$AUDIO_DIR/phrases/welcome/gute-reise.m4a"             "Gute Reise!"
gen "$AUDIO_DIR/phrases/welcome/bis-bald.m4a"               "Bis bald!"
gen "$AUDIO_DIR/phrases/welcome/brauchst-du-hilfe.m4a"      "Brauchst du Hilfe?"
gen "$AUDIO_DIR/phrases/welcome/koennen-sie-mir-helfen.m4a" "Können Sie mir helfen?"
gen "$AUDIO_DIR/phrases/welcome/noch-einmal-bitte.m4a"      "Noch einmal, bitte."
gen "$AUDIO_DIR/phrases/welcome/wie-schreibt-man-das.m4a"   "Wie schreibt man das?"
gen "$AUDIO_DIR/phrases/welcome/mein-name-ist.m4a"          "Mein Name ist Emma."

echo "== Chapter 1 phrases =="
gen "$AUDIO_DIR/phrases/chapter1/wie-heisst-du.m4a"          "Wie heißt du?"
gen "$AUDIO_DIR/phrases/chapter1/ich-heisse-nico.m4a"        "Ich heiße Nico."
gen "$AUDIO_DIR/phrases/chapter1/und-wie-heisst-du.m4a"      "Und wie heißt du?"
gen "$AUDIO_DIR/phrases/chapter1/ich-bin-lisa.m4a"           "Hallo, ich bin Lisa Brunner."
gen "$AUDIO_DIR/phrases/chapter1/das-ist-nico.m4a"           "Das ist Nico."
gen "$AUDIO_DIR/phrases/chapter1/nico-sucht-seine-tasche.m4a" "Nico sucht seine Tasche."
gen "$AUDIO_DIR/phrases/chapter1/wer-bist-du.m4a"            "Wer bist du?"
gen "$AUDIO_DIR/phrases/chapter1/woher-kommst-du.m4a"        "Woher kommst du?"
gen "$AUDIO_DIR/phrases/chapter1/ich-komme-aus-spanien.m4a"  "Ich komme aus Spanien."
gen "$AUDIO_DIR/phrases/chapter1/wo-wohnst-du.m4a"           "Wo wohnst du?"
gen "$AUDIO_DIR/phrases/chapter1/ich-wohne-in-sevilla.m4a"   "Ich wohne in Sevilla."
gen "$AUDIO_DIR/phrases/chapter1/nico-hat-ein-problem.m4a"   "Nico hat ein Problem."
gen "$AUDIO_DIR/phrases/chapter1/seine-tasche-ist-weg.m4a"   "Seine Tasche ist weg."
gen "$AUDIO_DIR/phrases/chapter1/seine-tante-wohnt.m4a"      "Seine Tante wohnt in Deutschland."

echo "== Chapter 2 phrases =="
gen "$AUDIO_DIR/phrases/chapter2/wie-alt-bist-du.m4a"          "Wie alt bist du?"
gen "$AUDIO_DIR/phrases/chapter2/ich-bin-jahre-alt.m4a"        "Ich bin zwanzig Jahre alt."
gen "$AUDIO_DIR/phrases/chapter2/sie-ist-acht.m4a"             "Sie ist acht."
gen "$AUDIO_DIR/phrases/chapter2/wie-ist-die-hausnummer.m4a"   "Wie ist die Hausnummer?"
gen "$AUDIO_DIR/phrases/chapter2/wie-ist-deine-telefonnummer.m4a" "Wie ist deine Telefonnummer?"
gen "$AUDIO_DIR/phrases/chapter2/meine-nummer-ist.m4a"         "Meine Nummer ist null acht null null sieben sieben sieben drei drei vier vier."
gen "$AUDIO_DIR/phrases/chapter2/zwei-oder-sieben.m4a"         "Ist das eine Zwei oder eine Sieben?"
gen "$AUDIO_DIR/phrases/chapter2/schreinerstrasse-144.m4a"     "Schreinerstraße hundertvierundvierzig."
gen "$AUDIO_DIR/phrases/chapter2/wagnergasse-136.m4a"          "Ich wohne in der Wagnergasse hundertsechsunddreißig."
gen "$AUDIO_DIR/phrases/chapter2/wie-kann-ich-ihnen-helfen.m4a" "Wie kann ich Ihnen helfen?"
gen "$AUDIO_DIR/phrases/chapter2/wie-ist-ihr-geburtsdatum.m4a" "Wie ist Ihr Geburtsdatum?"
gen "$AUDIO_DIR/phrases/chapter2/haben-sie-eine-adresse.m4a"   "Haben Sie eine Adresse?"
gen "$AUDIO_DIR/phrases/chapter2/ihre-passnummer.m4a"          "Ihre Passnummer?"
gen "$AUDIO_DIR/phrases/chapter2/herr-gonzalez.m4a"            "Herr González, freut mich sehr."

echo "Done."
